CREATE TABLE CLASS(ID INT PRIMARY KEY IDENTITY(1,1),CLASS VARCHAR(30));
SELECT * FROM CLASS
CREATE TABLE TEACHER(ID INT PRIMARY KEY IDENTITY(1,1),TEACH_REG VARCHAR(30),TEACHER_NAME VARCHAR(30),EMAIL VARCHAR(30),PHN_NO VARCHAR(30));
SELECT * FROM TEACHER
DROP TABLE TEACHER
CREATE TABLE SUBJECT(ID INT PRIMARY KEY IDENTITY(1,1),CLASS_ID INT FOREIGN KEY REFERENCES CLASS(ID),SUB_NAME VARCHAR(30),SUB_CODE VARCHAR(30));
SELECT * FROM SUBJECT
CREATE TABLE MARKDETAILES(ID INT PRIMARY KEY IDENTITY(1,1),TEACHER_ID INT FOREIGN KEY REFERENCES TEACHER(ID),SUB_ID INT FOREIGN KEY REFERENCES SUBJECT(ID),CLASS_ID INT FOREIGN KEY REFERENCES CLASS(ID),MARK INT,INERNAL_MARK INT,TOTAL_MARK INT);
SELECT * FROM MARKDETAILES