     select VFINE.ID,VFINE.VOILATION from VFINE inner join VTYPE on VFINE.TYPE_ID=VTYPE.ID inner join VEHICLE on VEHICLE.TYPE_ID =VTYPE.ID where VEHICLE.REG_NO='KL11235'
      select FINE from VFINE where ID=1
     select  FINEDETAILES.ID,FINEDETAILES.REG_NO,VEHICLE.REG_NAME,VEHICLE.ADDRESS,VEHICLE.PHN_NO,VEHICLE.EMAIL,VFINE.VOILATION,FINEDETAILES.FINE from VFINE
     inner join FINEDETAILES on VFINE.ID=FINEDETAILES.FINE_ID
	 inner join VEHICLE on FINEDETAILES.REG_NO=VEHICLE.REG_NO 

    select  FINEDETAILES.ID,FINEDETAILES.REG_NO,VEHICLE.REG_NAME,VEHICLE.ADDRESS,VEHICLE.PHN_NO,VEHICLE.EMAIL,VFINE.VOILATION,FINEDETAILES.FINE from VFINE inner join FINEDETAILES on VFINE.ID=FINEDETAILES.FINE_ID
	 inner join VEHICLE on FINEDETAILES.REG_NO=VEHICLE.REG_NO

     SELECT * FROM FINEDETAILES

     SELECT * FROM VEHICLE

     SELECT * FROM VFINE

     SELECT * FROM VTYPE

     select VFINE.ID,VFINE.VOILATION from VFINE inner join VTYPE on VFINE.TYPE_ID=VTYPE.ID inner join VEHICLE on VEHICLE.TYPE_ID =VTYPE.ID where VEHICLE.REG_NO='KL11235'